# Deployement of pod backend in stateless
apiVersion: apps/v1
kind: Deployment  # -> des pods stateless, on scale facilement
metadata:
  annotations:
    version : 0.2.0-SNAPSHOT
    devBy : LMare
  labels:
    app: backend
  name: backend
  namespace : lightning-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: LMare/lightning-playground-backend:v0.2.0-SNAPSHOT
          name: backend
          # TODO to delete to manage N lnd without modify config
          volumeMounts:
            - mountPath: /app/nodes-storage/.lnd1
              name: lnd1-data
            - mountPath: /app/nodes-storage/.lnd2
              name: lnd2-data
      restartPolicy: Always
      # TODO to delete to manage N lnd without modify config
      volumes:
        - name: lnd1-data
          persistentVolumeClaim:
            claimName: lnd1-data
        - name: lnd2-data
          persistentVolumeClaim:
            claimName: lnd2-data
