# Loadbalancer intern to access to a pod Backend
apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  namespace: lightning-playground
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: backend-entrypoint
    port: 80
    targetPort: backend-port
