# Ingress frontend: permet d'exposer le fontend vers l'ext√©rieur
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: lightning-playground
spec:
  rules:
  - host: lightning-playground.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service: frontend-loadbalancer
            port: frontend-entrypoint
