name: Go CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Installer Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'

    - name: Vérifier la compilation
      run: go build ./...

    - name: Lancer les tests
      run: go test -v ./...

    - name: Couverture des tests
      run: |
        go test -coverprofile=cover.out ./...
        # on filtre les fichiers générés *.pb.go
        grep -v "pb.go" cover.out > cover.filtered.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          file: cover.filtered.out
